export interface Product {
  id: number
  name: string
  category: string
  price: number
  originalPrice?: number
  image: string
  description: string
  features: string[]
  inStock: boolean
  rating: number
  reviews: number
}

export const products: Product[] = [
  {
    id: 1,
    name: "یخچال فریزر سامسونگ",
    category: "یخچال و فریزر",
    price: 45000000,
    originalPrice: 52000000,
    image: "/modern-samsung-refrigerator.jpg",
    description: "یخچال فریزر دوقلوی سامسونگ با فناوری نوفراست و ظرفیت 600 لیتر",
    features: ["فناوری نوفراست", "ظرفیت 600 لیتر", "کلاس انرژی A++", "کمپرسور اینورتر"],
    inStock: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    name: "ماشین لباسشویی ال‌جی",
    category: "لباسشویی",
    price: 28000000,
    image: "/modern-lg-washing-machine.jpg",
    description: "ماشین لباسشویی 9 کیلویی ال‌جی با فناوری بخار و درب کروم",
    features: ["ظرفیت 9 کیلوگرم", "فناوری بخار", "موتور اینورتر", "14 برنامه شستشو"],
    inStock: true,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: 3,
    name: "اجاق گاز اخوان",
    category: "اجاق گاز",
    price: 12500000,
    originalPrice: 14000000,
    image: "/modern-gas-stove.jpg",
    description: "اجاق گاز 5 شعله اخوان با صفحه شیشه‌ای و فر گازی",
    features: ["5 شعله", "صفحه شیشه‌ای", "فر گازی", "جرقه برقی"],
    inStock: true,
    rating: 4.5,
    reviews: 67,
  },
  {
    id: 4,
    name: "ماکروویو پاناسونیک",
    category: "ماکروویو",
    price: 8500000,
    image: "/modern-panasonic-microwave.jpg",
    description: "ماکروویو 32 لیتری پاناسونیک با فناوری اینورتر",
    features: ["ظرفیت 32 لیتر", "فناوری اینورتر", "گریل", "10 برنامه پخت"],
    inStock: true,
    rating: 4.7,
    reviews: 52,
  },
  {
    id: 5,
    name: "ماشین ظرفشویی بوش",
    category: "ظرفشویی",
    price: 35000000,
    image: "/modern-bosch-dishwasher.jpg",
    description: "ماشین ظرفشویی 14 نفره بوش با فناوری زئولیت",
    features: ["ظرفیت 14 نفره", "فناوری زئولیت", "کلاس انرژی A+++", "بسیار آرام"],
    inStock: false,
    rating: 4.9,
    reviews: 143,
  },
  {
    id: 6,
    name: "جاروبرقی سامسونگ",
    category: "جاروبرقی",
    price: 6500000,
    originalPrice: 7500000,
    image: "/modern-samsung-vacuum-cleaner.jpg",
    description: "جاروبرقی سامسونگ با فناوری سایکلون و فیلتر HEPA",
    features: ["فناوری سایکلون", "فیلتر HEPA", "قدرت 2000 وات", "بدون نیاز به کیسه"],
    inStock: true,
    rating: 4.4,
    reviews: 78,
  },
  {
    id: 7,
    name: "اتو بخار فیلیپس",
    category: "اتو",
    price: 3200000,
    image: "/modern-philips-steam-iron.jpg",
    description: "اتو بخار فیلیپس با کف سرامیکی و بخار عمودی",
    features: ["کف سرامیکی", "بخار عمودی", "قدرت 2400 وات", "ضد چکه"],
    inStock: true,
    rating: 4.3,
    reviews: 45,
  },
  {
    id: 8,
    name: "آبمیوه‌گیری مولینکس",
    category: "آبمیوه‌گیری",
    price: 4800000,
    image: "/modern-moulinex-juicer.jpg",
    description: "آبمیوه‌گیری مولینکس با قدرت 1200 وات و دهانه بزرگ",
    features: ["قدرت 1200 وات", "دهانه 75 میلیمتر", "2 سرعته", "قابل شستشو در ماشین"],
    inStock: true,
    rating: 4.5,
    reviews: 61,
  },
  {
    id: 9,
    name: "توستر دلونگی",
    category: "توستر",
    price: 2900000,
    originalPrice: 3400000,
    image: "/modern-delonghi-toaster.jpg",
    description: "توستر 4 اسلایس دلونگی با بدنه استیل",
    features: ["4 اسلایس", "بدنه استیل", "6 سطح برشتگی", "قابلیت لغو"],
    inStock: true,
    rating: 4.2,
    reviews: 34,
  },
  {
    id: 10,
    name: "قهوه‌ساز نسپرسو",
    category: "قهوه‌ساز",
    price: 15000000,
    image: "/modern-nespresso-coffee-machine.jpg",
    description: "قهوه‌ساز کپسولی نسپرسو با فشار 19 بار",
    features: ["فشار 19 بار", "مخزن 1 لیتر", "خاموش شدن خودکار", "سازگار با کپسول"],
    inStock: true,
    rating: 4.8,
    reviews: 156,
  },
  {
    id: 11,
    name: "هود آشپزخانه اخوان",
    category: "هود",
    price: 18000000,
    image: "/modern-kitchen-hood.jpg",
    description: "هود شومینه‌ای اخوان با قدرت مکش 1200 متر مکعب",
    features: ["قدرت مکش 1200 متر مکعب", "صفحه شیشه‌ای", "3 سرعته", "روشنایی LED"],
    inStock: true,
    rating: 4.6,
    reviews: 72,
  },
  {
    id: 12,
    name: "سشوار بابیلیس",
    category: "سشوار",
    price: 5500000,
    originalPrice: 6200000,
    image: "/modern-babyliss-hair-dryer.jpg",
    description: "سشوار حرفه‌ای بابیلیس با فناوری یونی",
    features: ["فناوری یونی", "قدرت 2300 وات", "6 تنظیم", "سرد و گرم"],
    inStock: true,
    rating: 4.7,
    reviews: 91,
  },
  {
    id: 13,
    name: "چرخ گوشت پارس خزر",
    category: "چرخ گوشت",
    price: 7200000,
    image: "/modern-meat-grinder.jpg",
    description: "چرخ گوشت پارس خزر با قدرت 2000 وات و بدنه فلزی",
    features: ["قدرت 2000 وات", "بدنه فلزی", "3 صفحه", "معکوس گردان"],
    inStock: true,
    rating: 4.4,
    reviews: 48,
  },
  {
    id: 14,
    name: "مخلط کن بوش",
    category: "مخلط کن",
    price: 9500000,
    image: "/modern-bosch-blender.jpg",
    description: "مخلط کن بوش با قدرت 1600 وات و پارچ شیشه‌ای",
    features: ["قدرت 1600 وات", "پارچ شیشه‌ای 2 لیتر", "تیغه استیل", "5 سرعته"],
    inStock: false,
    rating: 4.6,
    reviews: 83,
  },
  {
    id: 15,
    name: "آون توستر پارس خزر",
    category: "آون",
    price: 11000000,
    originalPrice: 12500000,
    image: "/modern-toaster-oven.jpg",
    description: "آون توستر 70 لیتری پارس خزر با گریل و کانوکشن",
    features: ["ظرفیت 70 لیتر", "گریل", "کانوکشن", "تایمر 120 دقیقه"],
    inStock: true,
    rating: 4.5,
    reviews: 56,
  },
  {
    id: 16,
    name: "پنکه دیجیتال پارس خزر",
    category: "پنکه",
    price: 4200000,
    image: "/modern-digital-fan.jpg",
    description: "پنکه دیجیتال پارس خزر با ریموت کنترل و تایمر",
    features: ["ریموت کنترل", "تایمر 12 ساعته", "3 سرعته", "نوسان 90 درجه"],
    inStock: true,
    rating: 4.3,
    reviews: 39,
  },
  {
    id: 17,
    name: "بخاری برقی دلونگی",
    category: "بخاری",
    price: 13500000,
    image: "/modern-delonghi-heater.jpg",
    description: "بخاری برقی دلونگی با ترموستات دیجیتال",
    features: ["ترموستات دیجیتال", "قدرت 2500 وات", "3 سطح حرارت", "ایمنی بالا"],
    inStock: true,
    rating: 4.7,
    reviews: 102,
  },
  {
    id: 18,
    name: "آبگرمکن برقی آریستون",
    category: "آبگرمکن",
    price: 22000000,
    originalPrice: 25000000,
    image: "/placeholder.svg?height=400&width=400",
    description: "آبگرمکن برقی 80 لیتری آریستون با عایق پلی‌اورتان",
    features: ["ظرفیت 80 لیتر", "عایق پلی‌اورتان", "ترموستات دیجیتال", "ضد خورگی"],
    inStock: true,
    rating: 4.8,
    reviews: 118,
  },
  {
    id: 19,
    name: "دستگاه تصفیه آب پاناسونیک",
    category: "تصفیه آب",
    price: 16500000,
    image: "/placeholder.svg?height=400&width=400",
    description: "دستگاه تصفیه آب پاناسونیک با 7 مرحله تصفیه",
    features: ["7 مرحله تصفیه", "فیلتر RO", "مخزن 12 لیتر", "نمایشگر دیجیتال"],
    inStock: true,
    rating: 4.9,
    reviews: 167,
  },
  {
    id: 20,
    name: "دستگاه بخور سرد بیورر",
    category: "بخور سرد",
    price: 3800000,
    originalPrice: 4300000,
    image: "/placeholder.svg?height=400&width=400",
    description: "دستگاه بخور سرد بیورر با ظرفیت 5 لیتر و نور شب",
    features: ["ظرفیت 5 لیتر", "نور شب", "خاموش شدن خودکار", "بسیار آرام"],
    inStock: true,
    rating: 4.5,
    reviews: 74,
  },
  {
    id: 21,
    name: "یخچال فریزر ال‌جی 500 لیتر",
    category: "یخچال و فریزر",
    price: 65000000,
    originalPrice: 72000000,
    image: "/images/product_21.jpg",
    description: "یخچال فریزر دوقلوی ال‌جی با فناوری Linear Compressor و ظرفیت 500 لیتر",
    features: ["ظرفیت 500 لیتر", "Linear Compressor", "کلاس انرژی A+", "DoorCooling+"],
    inStock: true,
    rating: 4.9,
    reviews: 203,
  },
  {
    id: 22,
    name: "ماشین ظرفشویی سامسونگ 15 نفره",
    category: "ظرفشویی",
    price: 45000000,
    image: "/images/product_22.jpg",
    description: "ماشین ظرفشویی سامسونگ با فناوری StormWash و ظرفیت 15 نفره",
    features: ["ظرفیت 15 نفره", "فناوری StormWash", "کلاس انرژی A+++", "Digital Inverter Motor"],
    inStock: true,
    rating: 4.8,
    reviews: 167,
  },
  {
    id: 23,
    name: "اتو بخار فیلیپس PerfectCare",
    category: "اتو",
    price: 4200000,
    originalPrice: 4800000,
    image: "/images/placeholder.jpg",
    description: "اتو بخار فیلیپس PerfectCare با فناوری OptimalTEMP و بخار عمودی",
    features: ["OptimalTEMP", "بخار عمودی", "کف T-ionicGlide", "قدرت 2400 وات"],
    inStock: true,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: 24,
    name: "قهوه‌ساز دلونگی EC685",
    category: "قهوه‌ساز",
    price: 18000000,
    image: "/modern-delonghi-coffee-maker.jpg",
    description: "قهوه‌ساز حرفه‌ای دلونگی با سیستم Cappuccino System و مخزن 1.8 لیتری",
    features: ["Cappuccino System", "مخزن 1.8 لیتری", "پمپ 15 بار", "موج دارکننده شیر"],
    inStock: true,
    rating: 4.7,
    reviews: 134,
  },
  {
    id: 25,
    name: "هود آشپزخانه فالکن",
    category: "هود",
    price: 25000000,
    originalPrice: 28000000,
    image: "/modern-falcon-hood.jpg",
    description: "هود شومینه‌ای فالکن با قدرت مکش 1200 متر مکعب و سیستم فیلتراسیون پیشرفته",
    features: ["قدرت مکش 1200 متر مکعب", "فیلتر آلومینیومی", "3 سرعته", "روشنایی LED"],
    inStock: true,
    rating: 4.5,
    reviews: 98,
  },
  {
    id: 26,
    name: "مخلط کن اوستیال BTA",
    category: "مخلط کن",
    price: 12000000,
    image: "/modern-ostial-blender.jpg",
    description: "مخلط کن حرفه‌ای اوستیال با قدرت 1400 وات و پارچ شیشه‌ای 2.3 لیتری",
    features: ["قدرت 1400 وات", "پارچ 2.3 لیتری", "تیغه استیل", "6 برنامه مختلف"],
    inStock: true,
    rating: 4.8,
    reviews: 156,
  },
  {
    id: 27,
    name: "توستر اوون سیفورت",
    category: "آون",
    price: 14000000,
    originalPrice: 16000000,
    image: "/modern-seifort-toaster-oven.jpg",
    description: "توستر اوون سیفورت با ظرفیت 65 لیتر و فناوری کانوکشن",
    features: ["ظرفیت 65 لیتر", "کانوکشن", "گریل", "تایمر دیجیتال"],
    inStock: true,
    rating: 4.6,
    reviews: 87,
  },
  {
    id: 28,
    name: "دستگاه تصفیه آب بریتا",
    category: "تصفیه آب",
    price: 22000000,
    image: "/modern-brita-water-filter.jpg",
    description: "دستگاه تصفیه آب بریتا با فیلتر میکروکربن و فناوری Claryum",
    features: ["فیلتر Claryum", "ظرفیت 10 کوپ", "کاهش کلر ۸۰%", "طعم طبیعی آب"],
    inStock: true,
    rating: 4.7,
    reviews: 142,
  },
  {
    id: 29,
    name: "جاروبرقی رباتیک سامسونگ",
    category: "جاروبرقی",
    price: 35000000,
    originalPrice: 40000000,
    image: "/modern-samsung-robotic-vacuum.jpg",
    description: "جاروبرقی رباتیک سامسونگ با ناوبری لیزری و قدرت مکش 2100 پاسکال",
    features: ["ناوبری لیزری", "قدرت مکش 2100 پاسکال", "باتری 90 دقیقه", "اپلیکیشن هوشمند"],
    inStock: true,
    rating: 4.9,
    reviews: 201,
  },
  {
    id: 30,
    name: "مایکروویو ال‌جی NeoChef",
    category: "ماکروویو",
    price: 12500000,
    image: "/modern-lg-microwave.jpg",

    // The following images will be available in the public folder:
    // - /modern-samsung-qled-tv.jpg
    // - /modern-asus-rog-laptop.jpg
    // - /modern-iphone-15-pro.jpg
    // - /modern-samsung-galaxy-tab-s9.jpg
    // - /modern-sony-wh1000xm5.jpg
    // - /modern-canon-eos-r6.jpg
    // - /modern-anker-power-bank.jpg
    // - /modern-keycool-mechanical-keyboard.jpg
    // - /modern-razer-deathadder-v3.jpg
    // - /modern-asus-rog-swift-monitor.jpg
    // - /modern-wd-external-hdd.jpg
    // - /modern-asus-rog-strix-pc.jpg
    // - /modern-samsung-laser-printer.jpg
    // - /modern-jbl-go3-speaker.jpg
    // - /modern-samsung-usb-flash.jpg
    // - /modern-asus-rtx4070.jpg
    // - /modern-corsair-ddr4-ram.jpg
    // - /modern-amd-ryzen7-7700x.jpg
    // - /modern-asus-rog-helios-case.jpg
    // - /modern-samsung-750w-psu.jpg
    // - /modern-oculus-quest2.jpg
    // - /modern-playstation5.jpg
    // - /modern-asus-rog-raikiri.jpg
    // - /modern-logitech-c920-webcam.jpg
    // - /modern-corsair-virtuoso-rgb.jpg
    // - /modern-samsung-970-evo-ssd.jpg
    // - /modern-corsair-h100i-cooler.jpg
    // - /modern-blue-yeti-microphone.jpg
    // - /modern-asus-rt-ax88u-router.jpg
    // - /modern-samsung-wireless-charger.jpg
    // - /modern-razer-blackwidow-v3.jpg
    // - /modern-htc-vive-pro2.jpg
    // - /modern-google-nest-audio.jpg
    // - /modern-anker-67w-charger.jpg
    // - /modern-asus-rog-ssd.jpg
    // - /modern-logitech-mx-master-3s.jpg
    // - /modern-nzxt-h510-case.jpg
    // - /modern-gigabyte-rtx4060ti.jpg
    // - /modern-intel-i5-13600k.jpg
    // - /modern-samsung-odyssey-g7.jpg
    description: "مایکروویو ال‌جی NeoChef با فناوری Smart Inverter و ظرفیت 42 لیتر",
    features: ["ظرفیت 42 لیتر", "Smart Inverter", "10 برنامه پخت", "کوره Charcoal Lighting Heater"],
    inStock: true,
    rating: 4.8,
    reviews: 113,
  },
  {
    id: 31,
    name: "تلویزیون سامسونگ QLED 55 اینچ",
    category: "تلویزیون",
    price: 45000000,
    originalPrice: 52000000,
    image: "/modern-samsung-qled-tv.jpg",
    description: "تلویزیون سامسونگ QLED 55 اینچ با فناوری Quantum Dot و کیفیت 4K",
    features: ["اندازه 55 اینچ", "کیفیت 4K", "فناوری QLED", "پشتیبانی HDR10+"],
    inStock: true,
    rating: 4.9,
    reviews: 245,
  },
  {
    id: 32,
    name: "لپ تاپ ایسوس ROG Gaming",
    category: "لپ تاپ",
    price: 65000000,
    image: "/modern-asus-rog-laptop.jpg",
    description: "لپ تاپ ایسوس ROG Gaming با پردازنده Intel Core i7 و کارت گرافیک RTX 3060",
    features: ["پردازنده Core i7", "کارت گرافیک RTX 3060", "رم 16GB", "صفحه نمایش 15.6 اینچ"],
    inStock: true,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 33,
    name: "گوشی موبایل آیفون 15 پرو",
    category: "گوشی موبایل",
    price: 85000000,
    originalPrice: 95000000,
    image: "/modern-iphone-15-pro.jpg",
    description: "گوشی موبایل آیفون 15 پرو با پردازنده A17 Pro و دوربین 48 مگاپیکسل",
    features: ["پردازنده A17 Pro", "دوربین 48MP", "صفحه نمایش Super Retina XDR", "تیتانیوم"],
    inStock: true,
    rating: 4.8,
    reviews: 312,
  },
  {
    id: 34,
    name: "تبلت سامسونگ Galaxy Tab S9",
    category: "تبلت",
    price: 28000000,
    image: "/modern-samsung-galaxy-tab-s9.jpg",
    description: "تبلت سامسونگ Galaxy Tab S9 با صفحه نمایش 11 اینچ و قلم S Pen",
    features: ["صفحه نمایش 11 اینچ", "قلم S Pen", "پردازنده Snapdragon 8 Gen 2", "باتری 8400mAh"],
    inStock: true,
    rating: 4.6,
    reviews: 156,
  },
  {
    id: 35,
    name: "هدفون سونی WH-1000XM5",
    category: "هدفون",
    price: 12000000,
    originalPrice: 14000000,
    image: "/modern-sony-wh1000xm5.jpg",
    description: "هدفون سونی WH-1000XM5 با فناوری حذف نویز فعال و کیفیت صدای بالا",
    features: ["حذف نویز فعال", "کیفیت صدای Hi-Res", "باتری 30 ساعت", "کنترل لمسی"],
    inStock: true,
    rating: 4.8,
    reviews: 278,
  },
  {
    id: 36,
    name: "دوربین کانن EOS R6",
    category: "دوربین",
    price: 95000000,
    image: "/modern-canon-eos-r6.jpg",
    description: "دوربین کانن EOS R6 با سنسور 20 مگاپیکسل و فیلمبرداری 4K",
    features: ["سنسور 20MP", "فیلمبرداری 4K", "ثبات تصویر 5 محوره", "صفحه نمایش لمسی"],
    inStock: false,
    rating: 4.9,
    reviews: 134,
  },
  {
    id: 37,
    name: "پاوربانک انکر 20000mAh",
    category: "پاوربانک",
    price: 4500000,
    originalPrice: 5500000,
    image: "/modern-anker-power-bank.jpg",
    description: "پاوربانک انکر با ظرفیت 20000 میلی‌آمپر و شارژ سریع",
    features: ["ظرفیت 20000mAh", "شارژ سریع", "پورت USB-C", "LED نمایشگر"],
    inStock: true,
    rating: 4.5,
    reviews: 423,
  },
  {
    id: 38,
    name: "کیبورد مکانیکی کی کولر",
    category: "کیبورد",
    price: 3200000,
    image: "/modern-keycool-mechanical-keyboard.jpg",
    description: "کیبورد مکانیکی کی کولر با سوئیچ‌های قرمز و نورپردازی RGB",
    features: ["سوئیچ مکانیکی قرمز", "نورپردازی RGB", "کلیدهای PBT", "آنتی گوستینگ"],
    inStock: true,
    rating: 4.4,
    reviews: 198,
  },
  {
    id: 39,
    name: "موس گیمینگ ریزر DeathAdder V3",
    category: "موس",
    price: 2200000,
    image: "/modern-razer-deathadder-v3.jpg",
    description: "موس گیمینگ ریزر DeathAdder V3 با سنسور 30000 DPI و سوئیچ‌های اپتیکال",
    features: ["سنسور 30000 DPI", "سوئیچ اپتیکال", "باتری 90 ساعت", "طراحی ارگونومیک"],
    inStock: true,
    rating: 4.7,
    reviews: 267,
  },
  {
    id: 40,
    name: "مانیتور ایسوس ROG Swift 27 اینچ",
    category: "مانیتور",
    price: 18000000,
    originalPrice: 21000000,
    image: "/modern-asus-rog-swift-monitor.jpg",
    description: "مانیتور ایسوس ROG Swift 27 اینچ با نرخ تازه‌سازی 144Hz و پنل IPS",
    features: ["اندازه 27 اینچ", "نرخ 144Hz", "پنل IPS", "زمان پاسخگویی 1ms"],
    inStock: true,
    rating: 4.8,
    reviews: 145,
  },
  {
    id: 41,
    name: "هارد دیسک اکسترنال وسترن دیجیتال 2TB",
    category: "هارد دیسک",
    price: 3800000,
    image: "/modern-wd-external-hdd.jpg",
    description: "هارد دیسک اکسترنال وسترن دیجیتال 2 ترابایت با اتصال USB 3.0",
    features: ["ظرفیت 2TB", "اتصال USB 3.0", "سرعت انتقال بالا", "طراحی مقاوم"],
    inStock: true,
    rating: 4.3,
    reviews: 312,
  },
  {
    id: 42,
    name: "رایانه شخصی ایسوس ROG Strix",
    category: "رایانه",
    price: 85000000,
    image: "/modern-asus-rog-strix-pc.jpg",
    description: "رایانه شخصی ایسوس ROG Strix با پردازنده Intel Core i9 و کارت گرافیک RTX 4070",
    features: ["پردازنده Core i9", "کارت گرافیک RTX 4070", "رم 32GB", "SSD 1TB"],
    inStock: true,
    rating: 4.9,
    reviews: 98,
  },
  {
    id: 43,
    name: "پرینتر لیزری سامسونگ",
    category: "پرینتر",
    price: 6500000,
    originalPrice: 7500000,
    image: "/modern-samsung-laser-printer.jpg",
    description: "پرینتر لیزری سامسونگ با سرعت چاپ 20 صفحه در دقیقه",
    features: ["سرعت 20ppm", "کیفیت 1200 DPI", "چاپ دو رو", "کارتریج توکار"],
    inStock: true,
    rating: 4.4,
    reviews: 156,
  },
  {
    id: 44,
    name: "اسپیکر بلوتوثی جی بی ال GO 3",
    category: "اسپیکر",
    price: 1800000,
    image: "/modern-jbl-go3-speaker.jpg",
    description: "اسپیکر بلوتوثی جی بی ال GO 3 با صدای قدرتمند و مقاوم در برابر آب",
    features: ["مقاوم در برابر آب", "باتری 5 ساعت", "بلوتوث 5.1", "صدا 360 درجه"],
    inStock: true,
    rating: 4.6,
    reviews: 534,
  },
  {
    id: 45,
    name: "فلاش مموری سامسونگ 128GB",
    category: "فلاش مموری",
    price: 450000,
    originalPrice: 550000,
    image: "/modern-samsung-usb-flash.jpg",
    description: "فلاش مموری سامسونگ 128 گیگابایت با سرعت انتقال بالا",
    features: ["ظرفیت 128GB", "سرعت USB 3.1", "طراحی جمع و جور", "گارانتی سامسونگ"],
    inStock: true,
    rating: 4.5,
    reviews: 678,
  },
  {
    id: 46,
    name: "کارت گرافیک ایسوس RTX 4070",
    category: "کارت گرافیک",
    price: 45000000,
    image: "/modern-asus-rtx4070.jpg",
    description: "کارت گرافیک ایسوس RTX 4070 با 12GB حافظه GDDR6X",
    features: ["حافظه 12GB GDDR6X", "پردازنده Ada Lovelace", "DLSS 3", "Ray Tracing"],
    inStock: false,
    rating: 4.9,
    reviews: 87,
  },
  {
    id: 47,
    name: "رم DDR4 کروشیال 16GB",
    category: "رم",
    price: 2200000,
    image: "/modern-corsair-ddr4-ram.jpg",
    description: "رم DDR4 کروشیال 16 گیگابایت با فرکانس 3200MHz",
    features: ["ظرفیت 16GB", "فرکانس 3200MHz", "تایمینگ CL16", "کولر آلومینیومی"],
    inStock: true,
    rating: 4.7,
    reviews: 203,
  },
  {
    id: 48,
    name: "پردازنده AMD Ryzen 7 7700X",
    category: "پردازنده",
    price: 12500000,
    image: "/modern-amd-ryzen7-7700x.jpg",
    description: "پردازنده AMD Ryzen 7 7700X با 8 هسته و فرکانس 4.5GHz",
    features: ["8 هسته / 16 رشته", "فرکانس پایه 4.5GHz", "حافظه کش 32MB", "پشتیبانی PCIe 5.0"],
    inStock: true,
    rating: 4.8,
    reviews: 145,
  },
  {
    id: 49,
    name: "کیس ایسوس ROG Strix Helios",
    category: "کیس کامپیوتر",
    price: 4500000,
    image: "/modern-asus-rog-helios-case.jpg",
    description: "کیس ایسوس ROG Strix Helios با پنل شیشه‌ای و نورپردازی RGB",
    features: ["پنل شیشه‌ای", "نورپردازی RGB", "پشتیبانی مادربرد ATX", "فن های 140mm"],
    inStock: true,
    rating: 4.6,
    reviews: 112,
  },
  {
    id: 50,
    name: "پاور سامسونگ 750 وات",
    category: "پاور",
    price: 2800000,
    originalPrice: 3200000,
    image: "/modern-samsung-750w-psu.jpg",
    description: "پاور سامسونگ 750 وات با گواهی 80 Plus Gold و مدولار",
    features: ["قدرت 750W", "گواهی 80 Plus Gold", "کابل های مدولار", "فن 120mm"],
    inStock: true,
    rating: 4.5,
    reviews: 98,
  },
  {
    id: 51,
    name: "هدست واقعیت مجازی اوکولوس Quest 2",
    category: "واقعیت مجازی",
    price: 15000000,
    image: "/modern-oculus-quest2.jpg",
    description: "هدست واقعیت مجازی اوکولوس Quest 2 با کنترلرهای Touch",
    features: ["صفحه نمایش LCD", "زاویه دید 90 درجه", "باتری داخلی", "کنترلرهای Touch"],
    inStock: true,
    rating: 4.7,
    reviews: 324,
  },
  {
    id: 52,
    name: "کنسول بازی پلی استیشن 5",
    category: "کنسول بازی",
    price: 35000000,
    image: "/modern-playstation5.jpg",
    description: "کنسول بازی پلی استیشن 5 با قابلیت 4K و SSD سریع",
    features: ["پردازنده Zen 2", "SSD سفارشی", "پشتیبانی 4K", "کنترلر DualSense"],
    inStock: false,
    rating: 4.9,
    reviews: 567,
  },
  {
    id: 53,
    name: "گیم پد ایسوس ROG Raikiri",
    category: "گیم پد",
    price: 8500000,
    image: "/modern-asus-rog-raikiri.jpg",
    description: "گیم پد ایسوس ROG Raikiri با سوئیچ های مکانیکی و نورپردازی RGB",
    features: ["سوئیچ های مکانیکی", "نورپردازی RGB", "پشتیبانی Android", "باتری 65 ساعت"],
    inStock: true,
    rating: 4.6,
    reviews: 189,
  },
  {
    id: 54,
    name: "وبکم لاجیتک C920 HD",
    category: "وبکم",
    price: 1200000,
    image: "/modern-logitech-c920-webcam.jpg",
    description: "وبکم لاجیتک C920 HD با کیفیت 1080p و میکروفون استریو",
    features: ["کیفیت 1080p", "میکروفون استریو", "فوکوس خودکار", "پشتیبانی H.264"],
    inStock: true,
    rating: 4.4,
    reviews: 245,
  },
  {
    id: 55,
    name: "کارت صدا کروشیال Virtuoso RGB",
    category: "کارت صدا",
    price: 3500000,
    image: "/modern-corsair-virtuoso-rgb.jpg",
    description: "کارت صدا کروشیال Virtuoso RGB با میکروفون detachable",
    features: ["میکروفون detachable", "نورپردازی RGB", "کیفیت صدای 7.1", "آنتی ویبراسیون"],
    inStock: true,
    rating: 4.7,
    reviews: 176,
  },
  {
    id: 56,
    name: "SSD سامسونگ 970 EVO Plus 1TB",
    category: "SSD",
    price: 3800000,
    image: "/modern-samsung-970-evo-ssd.jpg",
    description: "SSD سامسونگ 970 EVO Plus 1 ترابایت با سرعت خواندن 3500MB/s",
    features: ["ظرفیت 1TB", "سرعت خواندن 3500MB/s", "نوشتن 3300MB/s", "گارانتی 5 سال"],
    inStock: true,
    rating: 4.8,
    reviews: 298,
  },
  {
    id: 57,
    name: "کیس خنک کننده کروشیال H100i Elite Capellix",
    category: "خنک کننده",
    price: 2800000,
    image: "/modern-corsair-h100i-cooler.jpg",
    description: "کیس خنک کننده مایع کروشیال H100i Elite Capellix با رادیاتور 240mm",
    features: ["رادیاتور 240mm", "پمپ قدرتمند", "فن های ML RGB", "سازگار با Intel/AMD"],
    inStock: true,
    rating: 4.6,
    reviews: 134,
  },
  {
    id: 58,
    name: "میکروفون یوتیوب بلیو Yeti USB",
    category: "میکروفون",
    price: 2200000,
    image: "/modern-blue-yeti-microphone.jpg",
    description: "میکروفون یوتیوب بلیو Yeti USB با کیفیت استودیویی",
    features: ["کیفیت استودیویی", "اتصال USB", "4 الگوی برداری", "پد میوت و فیلتر"],
    inStock: true,
    rating: 4.7,
    reviews: 456,
  },
  {
    id: 59,
    name: "روتر ایسوس RT-AX88U",
    category: "روتر",
    price: 6500000,
    image: "/modern-asus-rt-ax88u-router.jpg",
    description: "روتر ایسوس RT-AX88U با استاندارد Wi-Fi 6 و سرعت 6000Mbps",
    features: ["Wi-Fi 6", "سرعت 6000Mbps", "8 آنتن", "پورت های گیگابیتی"],
    inStock: true,
    rating: 4.5,
    reviews: 167,
  },
  {
    id: 60,
    name: "شارژر بی سیم سامسونگ",
    category: "شارژر بی سیم",
    price: 850000,
    image: "/modern-samsung-wireless-charger.jpg",
    description: "شارژر بی سیم سامسونگ با فناوری Fast Wireless Charging",
    features: ["شارژ سریع بی سیم", "سازگار با Qi", "LED نمایشگر", "طراحی جمع و جور"],
    inStock: true,
    rating: 4.3,
    reviews: 389,
  },
  {
    id: 61,
    name: "کیبورد مکانیکی ریزر BlackWidow V3",
    category: "کیبورد",
    price: 5500000,
    image: "/modern-razer-blackwidow-v3.jpg",
    description: "کیبورد مکانیکی ریزر BlackWidow V3 با سوئیچ سبز و نورپردازی RGB",
    features: ["سوئیچ مکانیکی سبز", "نورپردازی RGB", "آنتی گوستینگ", "پشتیبانی نرم افزاری"],
    inStock: true,
    rating: 4.8,
    reviews: 223,
  },
  {
    id: 62,
    name: "هدست واقعیت مجازی HTC Vive Pro 2",
    category: "واقعیت مجازی",
    price: 28000000,
    image: "/modern-htc-vive-pro2.jpg",
    description: "هدست واقعیت مجازی HTC Vive Pro 2 با رزولوشن 5K",
    features: ["رزولوشن 5K", "زاویه دید 120 درجه", "ردیابی 6DOF", "سازگار با SteamVR"],
    inStock: false,
    rating: 4.6,
    reviews: 98,
  },
  {
    id: 63,
    name: "اسپیکر هوشمند گوگل Nest Audio",
    category: "اسپیکر هوشمند",
    price: 2800000,
    image: "/modern-google-nest-audio.jpg",
    description: "اسپیکر هوشمند گوگل Nest Audio با دستیار گوگل",
    features: ["دستیار گوگل", "کیفیت صدای بالا", "کنترل لمسی", "سازگار با Chromecast"],
    inStock: true,
    rating: 4.4,
    reviews: 345,
  },
  {
    id: 64,
    name: "شارژر دیواری انکر 67W",
    category: "شارژر",
    price: 650000,
    image: "/modern-anker-67w-charger.jpg",
    description: "شارژر دیواری انکر 67 وات با پورت USB-C و Power Delivery",
    features: ["قدرت 67W", "Power Delivery 3.0", "پورت USB-C", "شارژ سریع"],
    inStock: true,
    rating: 4.6,
    reviews: 567,
  },
  {
    id: 65,
    name: "هارد SSD ایسوس ROG Strix 500GB",
    category: "SSD",
    price: 3200000,
    image: "/modern-asus-rog-ssd.jpg",
    description: "هارد SSD ایسوس ROG Strix 500 گیگابایت با سرعت NVMe",
    features: ["ظرفیت 500GB", "سرعت NVMe", "خواندن 7000MB/s", "نوشتن 5500MB/s"],
    inStock: true,
    rating: 4.7,
    reviews: 187,
  },
  {
    id: 66,
    name: "موس بی سیم لاجیتک MX Master 3S",
    category: "موس",
    price: 3800000,
    image: "/modern-logitech-mx-master-3s.jpg",
    description: "موس بی سیم لاجیتک MX Master 3S با سنسور Darkfield",
    features: ["سنسور Darkfield", "باتری 70 روز", "7 دکمه قابل برنامه ریزی", "MagSpeed Scroll"],
    inStock: true,
    rating: 4.8,
    reviews: 298,
  },
  {
    id: 67,
    name: "کیس خنک کننده NZXT H510",
    category: "کیس کامپیوتر",
    price: 1800000,
    image: "/modern-nzxt-h510-case.jpg",
    description: "کیس NZXT H510 با طراحی مینیمال و پنل شیشه‌ای",
    features: ["طراحی مینیمال", "پنل شیشه‌ای", "پشتیبانی ATX", "فن های از پیش نصب شده"],
    inStock: true,
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 68,
    name: "کارت گرافیک گیگابایت RTX 4060 Ti",
    category: "کارت گرافیک",
    price: 32000000,
    image: "/modern-gigabyte-rtx4060ti.jpg",
    description: "کارت گرافیک گیگابایت RTX 4060 Ti با 8GB حافظه GDDR6",
    features: ["حافظه 8GB GDDR6", "پردازنده Ada Lovelace", "DLSS 3", "Ray Tracing"],
    inStock: true,
    rating: 4.7,
    reviews: 123,
  },
  {
    id: 69,
    name: "پردازنده Intel Core i5-13600K",
    category: "پردازنده",
    price: 14500000,
    image: "/modern-intel-i5-13600k.jpg",
    description: "پردازنده Intel Core i5-13600K با 14 هسته و فرکانس 5.1GHz",
    features: ["14 هسته / 20 رشته", "فرکانس پایه 5.1GHz", "حافظه کش 24MB", "پشتیبانی DDR5"],
    inStock: true,
    rating: 4.8,
    reviews: 167,
  },
  {
    id: 70,
    name: "مانیتور سامسونگ Odyssey G7 32 اینچ",
    category: "مانیتور",
    price: 22000000,
    image: "/images/product_70.jpg",
    description: "مانیتور سامسونگ Odyssey G7 32 اینچ با نرخ 144Hz و پنل QHD",
    features: ["اندازه 32 اینچ", "نرخ 144Hz", "پنل QHD", "منحنی 1000R"],
    inStock: true,
    rating: 4.9,
    reviews: 189,
  },
  {
    id: 71,
    name: "یخچال ساید بای ساید ال‌جی",
    category: "یخچال و فریزر",
    price: 75000000,
    originalPrice: 95000000,
    image: "/images/product_71.jpg",
    description: "یخچال ساید بای ساید ال‌جی با فناوری DoorCooling+ و ظرفیت 600 لیتر",
    features: ["ظرفیت 600 لیتر", "DoorCooling+", "کلاس انرژی A+", "یخساز اتوماتیک"],
    inStock: true,
    rating: 4.8,
    reviews: 267,
  },
  {
    id: 72,
    name: "ماشین لباسشویی و خشک کن سامسونگ",
    category: "لباسشویی",
    price: 42000000,
    originalPrice: 55000000,
    image: "/images/product_72.jpg",
    description: "ماشین لباسشویی و خشک کن سامسونگ با فناوری EcoBubble",
    features: ["ظرفیت شستشو 9 کیلو", "ظرفیت خشک کن 6 کیلو", "EcoBubble", "14 برنامه"],
    inStock: true,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 73,
    name: "فر برقی دلونگی حرفه‌ای",
    category: "فر",
    price: 8500000,
    originalPrice: 11000000,
    image: "/images/product_73.jpg",
    description: "فر برقی دلونگی با فناوری کانوکشن و ظرفیت 65 لیتر",
    features: ["ظرفیت 65 لیتر", "کانوکشن", "10 برنامه پخت", "صفحه نمایش دیجیتال"],
    inStock: true,
    rating: 4.6,
    reviews: 145,
  },
  {
    id: 74,
    name: "ماکروفر پاناسونیک با گریل",
    category: "ماکروویو",
    price: 9500000,
    originalPrice: 12500000,
    image: "/images/product_74.jpg",
    description: "ماکروفر پاناسونیک با قابلیت گریل و ظرفیت 42 لیتر",
    features: ["ظرفیت 42 لیتر", "گریل", "اینورتر", "12 برنامه پخت"],
    inStock: true,
    rating: 4.5,
    reviews: 98,
  },
  {
    id: 75,
    name: "جاروبرقی سامسونگ با فیلتر HEPA",
    category: "جاروبرقی",
    price: 7500000,
    originalPrice: 9500000,
    image: "/images/product_75.jpg",
    description: "جاروبرقی سامسونگ با فیلتر HEPA و فناوری Cyclonic",
    features: ["فیلتر HEPA", "Cyclonic", "قدرت 2000 وات", "بدون کیسه"],
    inStock: true,
    rating: 4.7,
    reviews: 234,
  },
  {
    id: 76,
    name: "اتو بخار فیلیپس PerfectCare Elite",
    category: "اتو",
    price: 4800000,
    originalPrice: 6200000,
    image: "/images/product_76.jpg",
    description: "اتو بخار فیلیپس PerfectCare Elite با فناوری OptimalTEMP",
    features: ["OptimalTEMP", "بخار عمودی", "کف T-ionicGlide", "2400 وات"],
    inStock: true,
    rating: 4.8,
    reviews: 156,
  },
  {
    id: 77,
    name: "قهوه‌ساز کپسولی نسپرسو Vertuo",
    category: "قهوه‌ساز",
    price: 18500000,
    originalPrice: 22000000,
    image: "/images/product_77.jpg",
    description: "قهوه‌ساز کپسولی نسپرسو Vertuo با فناوری Centrifusion",
    features: ["Centrifusion", "مخزن 1.7 لیتر", "فشار 19 بار", "سازگار با کپسول"],
    inStock: true,
    rating: 4.9,
    reviews: 312,
  },
  {
    id: 78,
    name: "هود آشپزخانه با لامپ LED",
    category: "هود",
    price: 19500000,
    originalPrice: 24000000,
    image: "/images/product_78.jpg",
    description: "هود آشپزخانه مدرن با قدرت مکش 1200 متر مکعب و نورپردازی LED",
    features: ["قدرت مکش 1200 متر مکعب", "نورپردازی LED", "3 سرعته", "شستشو آسان"],
    inStock: true,
    rating: 4.6,
    reviews: 87,
  },
  {
    id: 79,
    name: "توستر چهار اسلایس دلونگی",
    category: "توستر",
    price: 3200000,
    originalPrice: 4200000,
    image: "/images/product_79.jpg",
    description: "توستر چهار اسلایس دلونگی با سطح برشتگی قابل تنظیم",
    features: ["4 اسلایس", "6 سطح برشتگی", "قابلیت لغو", "بدنه استیل"],
    inStock: true,
    rating: 4.4,
    reviews: 123,
  },
  {
    id: 80,
    name: "آون توستر گازی سامسونگ",
    category: "آون",
    price: 12500000,
    originalPrice: 15500000,
    image: "/images/product_80.jpg",
    description: "آون توستر گازی سامسونگ با قابلیت گریل و تایمر",
    features: ["ظرفیت 75 لیتر", "گریل", "تایمر", "ترموستات دیجیتال"],
    inStock: true,
    rating: 4.5,
    reviews: 198,
  },
  {
    id: 81,
    name: "دستگاه بخور سرد بیورر حرفه‌ای",
    category: "بخور سرد",
    price: 4200000,
    originalPrice: 5200000,
    image: "/images/product_81.jpg",
    description: "دستگاه بخور سرد بیورر با ظرفیت 5.5 لیتر و فیلتر HEPA",
    features: ["ظرفیت 5.5 لیتر", "فیلتر HEPA", "نور شب", "خاموش خودکار"],
    inStock: true,
    rating: 4.7,
    reviews: 145,
  },
  {
    id: 82,
    name: "پنکه ایستاده با ریموت کنترل",
    category: "پنکه",
    price: 4800000,
    originalPrice: 5800000,
    image: "/images/product_82.jpg",
    description: "پنکه ایستاده با 3 پروانه و ریموت کنترل دیجیتال",
    features: ["3 پروانه", "ریموت کنترل", "تایمر 12 ساعته", "نوسان 90 درجه"],
    inStock: true,
    rating: 4.3,
    reviews: 167,
  },
  {
    id: 83,
    name: "آبمیوه‌گیری کند مولینکس",
    category: "آبمیوه‌گیری",
    price: 5200000,
    originalPrice: 6500000,
    image: "/images/product_83.jpg",
    description: "آبمیوه‌گیری کند مولینکس با قدرت 40 وات و ظرف شیشه‌ای",
    features: ["قدرت 40 وات", "ظرف شیشه‌ای", "فیلتر", "شستشو آسان"],
    inStock: true,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: 84,
    name: "بخاری گازی دیواری",
    category: "بخاری",
    price: 16500000,
    originalPrice: 19500000,
    image: "/images/product_84.jpg",
    description: "بخاری گازی دیواری با سیستم ایمنی و ترموستات دیجیتال",
    features: ["سیستم ایمنی", "ترموستات دیجیتال", "بازدهی بالا", "نصب آسان"],
    inStock: true,
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 85,
    name: "چرخ گوشت برقی پارس خزر",
    category: "چرخ گوشت",
    price: 7800000,
    originalPrice: 9500000,
    image: "/images/product_85.jpg",
    description: "چرخ گوشت برقی پارس خزر با قدرت 2000 وات و 3 صفحه",
    features: ["قدرت 2000 وات", "3 صفحه", "معکوس گردان", "بدنه فلزی"],
    inStock: true,
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 86,
    name: "مخلط کن بوش ErgoMixx",
    category: "مخلط کن",
    price: 10500000,
    originalPrice: 12500000,
    image: "/images/product_86.jpg",
    description: "مخلط کن بوش ErgoMixx با قدرت 1600 وات و پارچ 2.3 لیتری",
    features: ["قدرت 1600 وات", "پارچ 2.3 لیتر", "تیغه استیل", "9 سرعته"],
    inStock: true,
    rating: 4.7,
    reviews: 178,
  },
  {
    id: 87,
    name: "فر یخچال سامسونگ",
    category: "فر",
    price: 9500000,
    originalPrice: 11500000,
    image: "/images/product_87.jpg",
    description: "فر یخچال سامسونگ با قابلیت فریزر و حجم 300 لیتر",
    features: ["حجم 300 لیتر", "فریزر", "کلاس انرژی A+", "قفل کودک"],
    inStock: true,
    rating: 4.6,
    reviews: 145,
  },
  {
    id: 88,
    name: "سشوار حرفه‌ای بابیلیس Pro",
    category: "سشوار",
    price: 6200000,
    originalPrice: 7500000,
    image: "/images/product_88.jpg",
    description: "سشوار حرفه‌ای بابیلیس Pro با فناوری یونی و قدرت 2400 وات",
    features: ["قدرت 2400 وات", "یونی", "6 تنظیم دما", "بدنه ارگونومیک"],
    inStock: true,
    rating: 4.8,
    reviews: 198,
  },
  {
    id: 89,
    name: "دستگاه تصفیه آب خانگی",
    category: "تصفیه آب",
    price: 18500000,
    originalPrice: 22000000,
    image: "/images/product_89.jpg",
    description: "دستگاه تصفیه آب خانگی با 6 مرحله فیلتراسیون",
    features: ["6 مرحله فیلتراسیون", "ظرفیت 12 لیتر", "UV", "نمایشگر دیجیتال"],
    inStock: true,
    rating: 4.9,
    reviews: 267,
  },
  {
    id: 90,
    name: "آبگرمکن برقی آریستون",
    category: "آبگرمکن",
    price: 24000000,
    originalPrice: 28000000,
    image: "/images/product_90.jpg",
    description: "آبگرمکن برقی آریستون با ظرفیت 80 لیتر و کلاس انرژی A",
    features: ["ظرفیت 80 لیتر", "کلاس انرژی A", "ترموستات دیجیتال", "ضد خوردگی"],
    inStock: true,
    rating: 4.7,
    reviews: 189,
  },
]
